version: '3.4'

services:

  nextjs:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: side-stacker-node-nextjs
    environment:
      - ENV
    volumes:
      - ./:/app
      
    ports:
      - 3000:3000
    # command: python3 src/side_stacker/sanic_app.py
